name: "Rm Release GitHub Action"
description: "A GitHub action to remove releases with their tags based on a regex pattern."
author: "nikhilbadyal"
inputs:
  GITHUB_TOKEN:
    required: true
    description: "Github token"
  RELEASE_PATTERN:
    required: true
    description: "Regex pattern to match releases."
  RELEASES_TO_KEEP:
    required: false
    description: "Number of most recent releases to keep after filtering by RELEASE_PATTERN. Defaults to 0 (delete all matching releases)."
    default: "0"
  EXCLUDE_PATTERN:
    required: false
    description: "Regex pattern to exclude releases from deletion."
  DAYS_TO_KEEP:
    required: false
    description: "Number of days to keep releases. Releases older than this will be deleted. Defaults to 0 (delete all matching releases regardless of age)."
    default: "0"
  DRY_RUN:
    required: false
    description: "If true, the action will only list the releases to be deleted without actually deleting them."
    default: false

branding:
  icon: "trash"
  color: "red"

runs:
  using: "node20"
  main: "dist/index.js"
