[version]
current = "v0.2.0"
regex = '''
  v(?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "{new_version}"

[[file]]
src = "package.json"
search = '"version": "{current_version}",'

[[file]]
src = "README.md"
search = "uses: nikhilbadyal/ghaction-rm-releases@{current_version}"

[[before_commit]]
name = "Build action"
cmd = "yarn all"
