name: Tests

on:
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Run tests
        run : |
          yarn install
          yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2.1.0
